### PR TITLE
Add typographing.

### PR DESCRIPTION
**Pull request by denysdovhan**
Introduce typograhing using `mdast-textr`.

### CODE REVIEW

**Comment by iamstarkov** [comment]
how does it feel after awhile?

**Comment by denysdovhan** [comment]
Nice enough. Problems were not noticed.

Maybe that's because I mainly use  just quotes and dashes, so it works fine with them. Not sure there aren't any problems with other cases.

**Comment by iamstarkov** [comment]
can you show me sample with dashes?

**Comment by denysdovhan** [comment]
Sure. Look at ["Hello, World! Again."](http://denysdovhan.com/hello-world/)

image

**Comment by iamstarkov** [comment]
very-very good

**Comment by iamstarkov** [comment]
Tåck sa mycket!

**Comment by denysdovhan** [comment]
На здоров’я :smirk:

**Pull request merged**
